from typing import List, Optional, Sequence, Union
from .controller import MakxdController
from .keyboard import Keyboard, KeyboardKey
from .stream import (
    StreamKind, StreamOperation, StreamTiming, StreamFrame,
    StreamControl, StreamInputRecord, StreamRequest, StreamFrameDecoder,
    decode_stream_control, decode_stream_input_record, STREAM_MASK_MOUSE,
    STREAM_MASK_KEYBOARD, STREAM_MASK_CONTROLLER, STREAM_MASK_ALL,
    STREAM_COMMAND_INPUT, STREAM_MAX_BODY_BYTES,
    STREAM_MAX_PAYLOAD_BYTES,
)

KeyboardKey = Union[int, str]

class Keyboard:
    def down(self, key: KeyboardKey) -> None: ...
    def up(self, key: KeyboardKey) -> None: ...
    def press(self, key: KeyboardKey, hold_ms: Optional[int] = ..., rand_ms: Optional[int] = ...) -> None: ...
    def string(self, text: str) -> None: ...
    def init(self) -> None: ...
    def is_down(self, key: KeyboardKey) -> bool: ...
    def mask(self, key: KeyboardKey, enable: bool) -> None: ...
    def remap(self, source: KeyboardKey, target: KeyboardKey) -> None: ...
    def multi_down(self, keys: Sequence[KeyboardKey]) -> None: ...
    def multi_up(self, keys: Sequence[KeyboardKey]) -> None: ...
    def multi_press(self, keys: Sequence[KeyboardKey]) -> None: ...
    def keys(self, enabled: Optional[bool] = ...) -> Optional[str]: ...

__version__: str
__all__: List[str]

def create_controller(
    fallback_com_port: str = "", 
    debug: bool = False, 
    send_init: bool = True
) -> MakxdController: ...
